Wazo 2671 wazo confd cli
wazo-platform/wazo-confd-cli pull request #2
Opened 2022-02-01 13:27 UTC by pc-m

2022-02-01 13:31 UTC, pc-m commented
recheck

2022-02-01 13:39 UTC, pc-m commented
recheck

2022-02-03 20:04 UTC, sduthil requested changes
I think a `--prefix` option would be nice too, in order to use `wazo-confd-cli` from another machine, e.g. with Docker:
```
docker run -it wazoplatform/wazo-confd-cli --hostname wazo.example.com --port 443 --prefix /api/confd --token mytoken user list
```

2022-02-03 20:04 UTC, sduthil commented on wazo_confd_cli/commands/endpoint.py
> +            def predicate(item):
```suggestion
            def has_template(item):
```

2022-02-03 20:04 UTC, sduthil commented on wazo_confd_cli/commands/endpoint.py
> +            raw_items = [item for item in raw_items if predicate(item)]
```suggestion
            raw_items = [item for item in raw_items if has_template(item)]
```

2022-02-03 20:10 UTC, sduthil commented
Also, when trying the `wazo-confd-cli`, there is always an error message at the start (even though the CLI commands are working):

```
Could not read config dir /root/.config/wazo-confd-cli: [Errno 2] No such file or directory: '/root/.config/wazo-confd-cli'
```

2022-02-03 20:13 UTC, sduthil commented on wazo_confd_cli/commands/endpoint.py
> +        headers = self.extract_column_headers(raw_items[0])
There is no validation that `raw_items` is empty.
If I run `wazo-confd-cli ... endpoint sip list --template does-not-exist`, then I get a Traceback on this line.

2022-02-04 14:34 UTC, pc-m commented
Thanks for the review, I fixed all reported problems. Some of them have been force pushed into the commit that adds the `--template` argument. I also changed the parsing of the https options because we could not specify the `https` and `verify_certificate` options that were in a mutually exclusive group

2022-02-04 16:52 UTC, sduthil approved these changes

2022-02-04 16:55 UTC, merged