Wp 525 enable video for webrtc
wazo-platform/wazo-confd-cli pull request #3
Opened 2022-02-01 19:15 UTC by pc-m

2022-02-03 20:28 UTC, sduthil requested changes

2022-02-03 20:28 UTC, sduthil commented on contribs/examples/enabled-video.sh
> +if [[ ! -v TENANT_UUID ]]; then
This condition is also true if `$TENANT_UUID=''`. So I think `[ -z "$TENANT_UUID" ]` would be better.

2022-02-03 20:28 UTC, sduthil commented on contribs/examples/enabled-video.sh
> +if ! command -v wazo-auth-cli &> /dev/null; then
Nice! I did not know about the `command -v` trick! Thank you!

2022-02-03 20:28 UTC, sduthil commented on contribs/examples/enabled-video.sh
> +    echo -n "Password: "
```suggestion
    echo -n "Password for $AUTH_USERNAME: "
```

2022-02-03 20:28 UTC, sduthil commented on contribs/examples/enabled-video.sh
> +readarray -t WEBRTC_VIDEO_ENDPOINT_UUIDS < <(wazo-confd-cli --token ${TOKEN} endpoint sip list --template ${WEBRTC_VIDEO_TEMPLATE_UUID} --tenant ${TENANT_UUID} -f value | awk -F ' ' '{ print $1 }')
```suggestion
readarray -t WEBRTC_VIDEO_ENDPOINT_UUIDS < <(wazo-confd-cli --token ${TOKEN} endpoint sip list --template ${WEBRTC_VIDEO_TEMPLATE_UUID} --tenant ${TENANT_UUID} -f value -c uuid')
```

2022-02-03 20:28 UTC, sduthil commented on contribs/examples/enabled-video.sh
> +for endpoint_uuid in $(wazo-confd-cli --token ${TOKEN} endpoint sip list --template ${WEBRTC_TEMPLATE_UUID} --tenant ${TENANT_UUID} -f value | awk -F ' ' '{ print $1 }'); do
```suggestion
for endpoint_uuid in $(wazo-confd-cli --token ${TOKEN} endpoint sip list --template ${WEBRTC_TEMPLATE_UUID} --tenant ${TENANT_UUID} -f value -c uuid); do
```

2022-02-04 19:48 UTC, pc-m commented on contribs/examples/enabled-video.sh
> +readarray -t WEBRTC_VIDEO_ENDPOINT_UUIDS < <(wazo-confd-cli --token ${TOKEN} endpoint sip list --template ${WEBRTC_VIDEO_TEMPLATE_UUID} --tenant ${TENANT_UUID} -f value | awk -F ' ' '{ print $1 }')
very nice, thanks for the info

2022-02-07 16:21 UTC, sduthil approved these changes

2022-02-07 17:24 UTC, merged